pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'maven:3.8.6-openjdk-17'
    }

    triggers {
        cron('H/2 * * * *') // Runs every 2 minutes
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/pascaleli/TaskManagementJava.git'
            }
        }

        stage('Build') {
            steps {
                dir('TaskManagementSystem') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('TaskManagementSystem') {
                    sh 'mvn test'
                }
            }
        }
    }

    post {
        always {
            dir('TaskManagementSystem') {
                junit '**/target/surefire-reports/*.xml'
            }
        }
    }
}
